[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#11121D"
foreground = "#a9b1d6"

[cursor.style]
shape = "Block"

[font]
size = 13.5

[font.bold]
family = "BitstromWera Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BitstromWera Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BitstromWera Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BitstromWera Nerd Font Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-D", "-s", " Home"]

[window]
dynamic_title = true
opacity = 0.85
startup_mode = "Windowed"
title = "Alacritty"
decorations = "Full"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[window.position]
x = 600
y = 200

[terminal]
