[[manager.prepend_keymap]]
on = "<C-y>"
run = 'arrow -10%'

[[manager.prepend_keymap]]
on = "<C-e>"
run = 'arrow 10%'

[[manager.prepend_keymap]]
on   = "<C-o>"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/SDU/year1/WS"
desc = "Go to the current semester at SDU"

[[manager.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/work"
desc = "Go to the work directory"

