-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- autogenerated = 1 -- remove this line to remove the warning

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

-- ################
-- ### MONITORS ###
-- ################

-- See https://wiki.hypr.land/Configuring/Monitors/
hl.monitor({
	output = "eDP-1",
	mode = "1920x1080",
	position = "0x0",
	scale = 1,
	bitdepth = 10,
})

hl.monitor({
	output = "DP-9",
	mode = "1920x1080",
	position = "1920x0",
	scale = 1,
	bitdepth = 10,
})

hl.monitor({
	output = "DP-9",
	mode = "1920x1080",
	position = "1920x0",
	scale = 1,
	bitdepth = 10,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080",
	position = "1920x0",
	scale = 1,
	mirror = "eDP-1",
	bitdepth = 10,
})

-- ###################
-- ##-- MY PROGRAMS ###
-- ###################

-- See https://wiki.hypr.land/Configuring/Keywords/
local terminal = "kitty"
local fileManager = "dolphin"
local menu = "pkill rofi || ~/.config/rofi/launch"
local switch_win = "pkill rofi || ~/.config/rofi/launch window"
local file_menu = "pkill rofi || ~/.config/rofi/launch filebrowser"

-- #################
-- ##-- AUTOSTART ###
-- #################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = waybar
-- exec-once = systemctl --user start hyprpolkitagent

-- exec-once = wl-paste --type text --watch cliphist store -- Stores only text data
-- exec-once = wl-paste --type image --watch cliphist store -- Stores only image data

-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox
hl.on("hyprland.start", function()
	hl.exec_cmd(terminal)
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("waybar")
	hl.exec_cmd("hyprpaper") -- & firefox
end)

-- #############################
-- ##-- ENVIRONMENT VARIABLES ###
-- #############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("XCURSOR_SIZE", "13")
hl.env("HYPRCURSOR_SIZE", "13")


-- ###################
-- ##-- PERMISSIONS ###
-- ###################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


-- #####################
-- ##-- LOOK AND FEEL ###
-- #####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general
hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 5,

		border_size = 1,

		-- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
		col = {
			active_border = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45, },
			inactive_border = "rgba(595959aa)",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "dwindle",
	},

	-- https://wiki.hypr.land/Configuring/Variables/#decoration
	decoration = {
		rounding = 8,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = false,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},

		-- https://wiki.hypr.land/Configuring/Variables/#blur
		blur = {
			enabled = false,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},

	-- https://wiki.hypr.land/Configuring/Variables/#animations
	animations = {
		enabled = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

hl.config({
	group = {
		auto_group = true,
		insert_after_current = true,
		focus_removed_window = true,
		col = {
			border_active = 0x6694e2d5,
			border_inactive = 0x66181825,
			border_locked_active = 0x66ff5500,
			border_locked_inactive = 0x66775500,
		},

		groupbar = {
			enabled = true,
			font_size = 13,
			gradients = false,
			indicator_gap = 1,
			stacked = false,
			rounding = 1,
			gradient_rounding = 3,
			round_only_edges = false,
			gradient_round_only_edges = false,
			col = {
				active = 0x6694e2d5,
				inactive = 0x66181825,
				locked_active = 0x66ff5500,
				locked_inactive = 0x66775500,
			},
		},
	},
})

hl.config({
	binds = {
		workspace_back_and_forth = false,
		allow_workspace_cycles = true,
		pass_mouse_when_bound = false,
	}
})

	-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true -- You probably want this
	},

	-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
	master = {
		-- new_status = master
	}
})

-- https://wiki.hypr.land/Configuring/Variables/#misc
hl.config({
	misc = {
		font_family = "BitstromWera Nerd Font Mono",
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_autoreload = true,
		disable_hyprland_logo = false,-- If true disables the random hyprland logo / anime girl background. :(
		vrr = 3,
		key_press_enables_dpms = true,
	},
})

hl.config({
	render = {
		new_render_scheduling = false,
	}
})

-- #############
-- ### INPUT ###
-- #############
-- https://wiki.hypr.land/Configuring/Variables/#input
hl.config({
	input = {
		kb_layout = "us,sk,dk",
		kb_variant = ",qwerty",

		follow_mouse = 1,
		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		numlock_by_default = true,

		touchpad = {
			natural_scroll = true,
		},
	}
})

-- See https://wiki.hypr.land/Configuring/Gestures
hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})


-- ###################
-- ##-- KEYBINDINGS ###
-- ###################

require("hyprkeymaps")

-- ##############################
-- ##-- WINDOWS AND WORKSPACES ###
-- ##############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrules that are useful

hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = {
		class = ".*",
	},

	suppress_event = "maximize",
})

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",

	match = {
		class = "hyprland-run",
	},

	move = { "20", "monitor_h-120" },
	float = true,
})

hl.window_rule({
	name = "move-spotify",
	match = {
		initial_class = "spotify",
	},

	monitor = "eDP-1",
	workspace = "10",
})

hl.window_rule({
	name = "move-callendar",
	match = {
		initial_class = "org.gnome.Calendar",
	},

	workspace = "9",
})

hl.workspace_rule({
	workspace = "9",
	default_name = "",
	on_created_empty = "gnome-calendar"
})

hl.workspace_rule({
	workspace = "10",
	default_name = "",
	on_created_empty = "spotify-launcher",
	monitor = "eDP-1",
})
