-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- autogenerated = 1 -- remove this line to remove the warning

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

-- ################
-- ### MONITORS ###
-- ################

-- See https://wiki.hypr.land/Configuring/Monitors/
local monitors = require("hyprland.monitor")
monitors:setup()


-- #################
-- ### AUTOSTART ###
-- #################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("waybar")
	hl.exec_cmd("~/.config/hypr/scripts/batter_notifier")
	hl.exec_cmd("wl-paste --type text --watch cliphist store") -- Stores only text data
	hl.exec_cmd("wl-paste --type image --watch cliphist store") -- Stores only image data

	hl.exec_cmd("kdeconnectd")
	hl.exec_cmd("kdeconnect-indicator")
end)

-- #############################
-- ### ENVIRONMENT VARIABLES ###
-- #############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("XCURSOR_SIZE", "13")
hl.env("HYPRCURSOR_SIZE", "13")


-- #####################
-- ### LOOK AND FEEL ###
-- #####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/
-- https://wiki.hypr.land/Configuring/Variables/#general
hl.config(require("hyprland.config") or {})

local animation = require("hyprland.animation")
animation.setup_curves()
animation.setup_animations()

-- See https://wiki.hypr.land/Configuring/Gestures
hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

-- This is how to make thisone work with the "One by Wacom":
--
-- $ yay -S opentabletdriver
-- $ echo "blacklist wacom" | sudo tee /etc/modprobe.d/no-wacom.conf
-- $ sudo mkinitcpio -P
-- $ systemctl --user enable --now opentabletdriver
--
-- # Now reboot
--
-- If needed change the name or the output.
hl.device({
	name = "opentabletdriver-virtual-artist-tablet",
	output = "DP-9",
})


-- ###################
-- ### KEYBINDINGS ###
-- ###################

require("hyprland.keymaps")

-- ##############################
-- ### WINDOWS AND WORKSPACES ###
-- ##############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = {
		class = ".*",
	},

	suppress_event = "maximize",
})

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",

	match = {
		class = "hyprland-run",
	},

	move = { "20", "monitor_h-120" },
	float = true,
})

hl.window_rule({
	name = "move-spotify",
	match = {
		-- Detected using `hyprctl clients`.
		class = "Spotify",
	},

	monitor = "eDP-1",
	workspace = "10",
})

hl.window_rule({
	name = "move-callendar",
	match = {
		initial_class = "org.gnome.Calendar",
	},

	workspace = "9",
})

hl.workspace_rule({
	workspace = "9",
	default_name = "",
	on_created_empty = "gnome-calendar"
})

hl.workspace_rule({
	workspace = "10",
	default_name = "",
	on_created_empty = "spotify-launcher",
	monitor = "eDP-1",
})
