#!/usr/bin/env bash

LAYOUT=
which hyprctl > /dev/null
if (( $? == 0)); then
	LAYOUT=$(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap')
else
	LAYOUT=$(swaymsg -t get_inputs | jq -r '.[] | select(.name=="AT Translated Set 2 keyboard") | .xkb_active_layout_name')
fi

case $LAYOUT in
	"English (US)")
		echo "EN"
		;;
	"Danish")
		echo "DK"
		;;
	"Slovak "|"Slovak (QWERTY)")
		echo "SK"
		;;
	*)
		echo "$LAYOUT"
		;;
esac

pkill -RTMIN+2 waybar
