#!/usr/bin/env bash

input="${1:-exec}"
profile=$(powerprofilesctl get)
profiles=("power-saver" "balanced" "performance")

declare -A profile_options=(
	["power-saver"]=" Power Saver"
	["balanced"]=" Balanced"
	["performance"]="󰊗 Performance"
)

declare -A reverse_profile_options=(
	["󰊗 Performance"]="performance"
	[" Balanced"]="balanced"
	[" Power Saver"]="power-saver"
)

get_profile_index() {
	for i in "${!profiles[@]}"; do
		if [[ "${profiles[$i]}" == "$profile" ]]; then
			echo $i
			return
		fi
	done
	echo -1
}

current_index=$(get_profile_index)

get_pp_state() {
	local step=$1

	[[ -z $step ]] && step=0

	index=$(( (current_index + $step) % ${#profiles[@]} ))
	profile_tag=${profiles[$index]}
	profile=${profile_options[$profile_tag]}
	echo "$profile_tag"
}

case "$input" in
	"exec")
		printf '{"text":"%s","alt":"%s","class":"%s"}\n' "$profile" "$profile" "$profile"
		;;

	"next")
		profile=$(get_pp_state 1)
		powerprofilesctl set "$profile"
		;;

	"previous")
		profile=$(get_pp_state -1)
		powerprofilesctl set "$profile"
		;;

	"menu")
		options=()

		for profile_option in "${profiles[@]}"; do
			icon=${profile_options[$profile_option]}
			options+=("$icon")
		done

		choice=$(printf "%s\n%s\n%s\n" "${options[@]}" \
			| rofi \
				-dmenu \
				-theme $XDG_CONFIG_HOME/rofi/alt/powerprofile.rasi \
				-selected-row $((current_index)) \
				-monitor $(
					swaymsg -t get_workspaces \
					| jq -r '.[] | select(.focused) | .output'
				)
			)

		if [[ -n "$choice" ]]; then
			powerprofilesctl set "${reverse_profile_options[$choice]}"
		fi
		;;
	*)
		echo "Unknown command: $input"
		;;
esac

pkill -RTMIN+1 waybar
